name: Build & publish drill artifacts
on:
  push:
    tags:
      - 'v[0-9]*.[0-9]*.[0-9]*'

jobs:
  build_and_publish_for_macos:
    name: Publish for macOS platform
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          gradle publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx1024m


  build_and_publish_for_linux:
    name: Publish for Linux platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          gradle build
          gradle publishLinuxX64PublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

  build_and_publish_for_win:
    name: Publish for Windows platform (Windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        run: |
          gradle build
          gradle publishMingwX64PublicationToMavenRepository
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
